/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    FeatureForm: typeof import('./src/components/FeatureForm.vue')['default']
  }
}
