/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/FeatureCard copy.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    FeatureForm: typeof import('./src/components/FeatureForm.vue')['default']
    MilestoneCard: typeof import('./src/components/MilestoneCard.vue')['default']
    MilestoneForm: typeof import('./src/components/MilestoneForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
